### ISSUE TITLE
Help plugin overlays some elements

### ISSUE THREAD

**Issue by flauc** [Jaspero/jms-plugins#3]
![image](https://user-images.githubusercontent.com/4489834/107890123-8fa7c580-6f17-11eb-843f-5fe4dc757866.png)

Looks like even the all powerfull z-index doesn't solve this :(

**Comment by markotarnaj** [comment]
Fixed in https://github.com/Jaspero/jms/commit/cd24e76de3eaf2894fe6bb2e453945166f87fa71
